# Generated by Django 4.0.1 on 2022-01-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classmate',
            field=models.CharField(db_column='class', default='cs', max_length=15, verbose_name='class'),
        ),
    ]
