# Generated by Django 4.0.1 on 2022-01-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_sex_alter_student_classmate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], default=0, verbose_name='sex'),
        ),
    ]
